services:
  go-htmx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-htmx
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped